services:
  - type: web
    name: edutrack-backend
    runtime: node
    repo: https://github.com/priyankabhandari22/College-Discovery-Platform.git
    branch: main
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://college-discovery-platform-frontend-rho.vercel.app
      - key: CollegeDataSet
        sync: false
    healthCheckPath: /api/health
